/* eslint-disable */
/**
 * Generated Convex API stub.
 * This file will be auto-generated by `npx convex dev`.
 * For now, it provides type stubs to prevent build errors.
 */

import type { FunctionReference } from "convex/server";

// Stub API object - will be replaced by codegen
export const api = {
  auth: {
    getUser: {} as FunctionReference<"query">,
    isAuthenticated: {} as FunctionReference<"query">,
    getUserRole: {} as FunctionReference<"query">,
    ensureProfile: {} as FunctionReference<"mutation">,
    linkWallet: {} as FunctionReference<"mutation">,
    acceptTerms: {} as FunctionReference<"mutation">,
  },
  profiles: {
    get: {} as FunctionReference<"query">,
    me: {} as FunctionReference<"query">,
    upsert: {} as FunctionReference<"mutation">,
    update: {} as FunctionReference<"mutation">,
    isIncomplete: {} as FunctionReference<"query">,
  },
  projects: {
    listByOwner: {} as FunctionReference<"query">,
    get: {} as FunctionReference<"query">,
    create: {} as FunctionReference<"mutation">,
    update: {} as FunctionReference<"mutation">,
    remove: {} as FunctionReference<"mutation">,
    listSharedWith: {} as FunctionReference<"query">,
  },
  credits: {
    get: {} as FunctionReference<"query">,
    initialize: {} as FunctionReference<"mutation">,
    deduct: {} as FunctionReference<"mutation">,
    addPurchased: {} as FunctionReference<"mutation">,
    getTransactions: {} as FunctionReference<"query">,
  },
  status: {
    getServices: {} as FunctionReference<"query">,
    getActiveIncidents: {} as FunctionReference<"query">,
    getIncidentHistory: {} as FunctionReference<"query">,
    getMaintenanceMode: {} as FunctionReference<"query">,
    updateService: {} as FunctionReference<"mutation">,
  },
  notifications: {
    list: {} as FunctionReference<"query">,
    unreadCount: {} as FunctionReference<"query">,
    markAsRead: {} as FunctionReference<"mutation">,
    markAllAsRead: {} as FunctionReference<"mutation">,
    create: {} as FunctionReference<"mutation">,
    remove: {} as FunctionReference<"mutation">,
  },
  marketing: {
    getActive: {} as FunctionReference<"query">,
    getBookings: {} as FunctionReference<"query">,
    getByProject: {} as FunctionReference<"query">,
    create: {} as FunctionReference<"mutation">,
    approve: {} as FunctionReference<"mutation">,
    reject: {} as FunctionReference<"mutation">,
    activate: {} as FunctionReference<"mutation">,
  },
  categories: {
    listByProject: {} as FunctionReference<"query">,
    create: {} as FunctionReference<"mutation">,
    update: {} as FunctionReference<"mutation">,
    remove: {} as FunctionReference<"mutation">,
    reorder: {} as FunctionReference<"mutation">,
  },
  layers: {
    listByCategory: {} as FunctionReference<"query">,
    listByProject: {} as FunctionReference<"query">,
    create: {} as FunctionReference<"mutation">,
    updateWeight: {} as FunctionReference<"mutation">,
    updateName: {} as FunctionReference<"mutation">,
    markAsEffect: {} as FunctionReference<"mutation">,
    remove: {} as FunctionReference<"mutation">,
    getExclusions: {} as FunctionReference<"query">,
    createExclusion: {} as FunctionReference<"mutation">,
    deleteExclusion: {} as FunctionReference<"mutation">,
  },
  productPages: {
    getByProject: {} as FunctionReference<"query">,
    getBySlug: {} as FunctionReference<"query">,
    listLive: {} as FunctionReference<"query">,
    listFeatured: {} as FunctionReference<"query">,
    upsert: {} as FunctionReference<"mutation">,
    publish: {} as FunctionReference<"mutation">,
    unpublish: {} as FunctionReference<"mutation">,
  },
  generations: {
    listByProject: {} as FunctionReference<"query">,
    get: {} as FunctionReference<"query">,
    create: {} as FunctionReference<"mutation">,
    updateStatus: {} as FunctionReference<"mutation">,
    saveResults: {} as FunctionReference<"mutation">,
    remove: {} as FunctionReference<"mutation">,
    getComments: {} as FunctionReference<"query">,
    addComment: {} as FunctionReference<"mutation">,
  },
  admin: {
    isAdmin: {} as FunctionReference<"query">,
    getUsers: {} as FunctionReference<"query">,
    getPendingVerifications: {} as FunctionReference<"query">,
    approveVerification: {} as FunctionReference<"mutation">,
    rejectVerification: {} as FunctionReference<"mutation">,
    getBugReports: {} as FunctionReference<"query">,
    updateBugStatus: {} as FunctionReference<"mutation">,
    getMarketingRequests: {} as FunctionReference<"query">,
    getHeroBackgrounds: {} as FunctionReference<"query">,
    addHeroBackground: {} as FunctionReference<"mutation">,
    toggleHeroBackground: {} as FunctionReference<"mutation">,
    deleteHeroBackground: {} as FunctionReference<"mutation">,
    getArtFundStats: {} as FunctionReference<"query">,
  },
  files: {
    generateUploadUrl: {} as FunctionReference<"mutation">,
    saveFileMetadata: {} as FunctionReference<"mutation">,
    getUrl: {} as FunctionReference<"query">,
    deleteFile: {} as FunctionReference<"mutation">,
    uploadAvatar: {} as FunctionReference<"mutation">,
    uploadLayer: {} as FunctionReference<"mutation">,
    uploadProductAsset: {} as FunctionReference<"mutation">,
    uploadHeroBackground: {} as FunctionReference<"mutation">,
  },
} as const;

export const internal = {} as const;
