/* eslint-disable */
/**
 * Generated Convex data model stub.
 * This file will be auto-generated by `npx convex dev`.
 */

import type { GenericDataModel } from "convex/server";
export type DataModel = GenericDataModel;
