import { useQuery, useMutation } from 'convex/react';
import { api } from '../../convex/_generated/api';
import { Id } from '../../convex/_generated/dataModel';

export interface PaymentIntent {
  _id: Id<"payment_intents">;
  paymentId?: string;
  address?: string;
  amountLovelace?: number;
  amountAda?: number;
  displayAmount?: string;
  credits?: number;
  expiresAt?: string;
  payment_address: string;
  amount_ada: number;
  amount_lovelace: number;
  expires_at: string;
  status: string;
  type: string;
  tx_hash?: string;
  metadata?: Record<string, unknown>;
}

export interface PendingPayment {
  _id: Id<"payment_intents">;
  id?: string;
  tier_id?: string;
  credits_amount?: number;
  price_ada?: number;
  expected_amount_lovelace?: number;
  status: string;
  tx_hash?: string;
  created_at?: string;
  expires_at: string;
  completed_at?: string;
  amount_ada: number;
  amount_lovelace: number;
}

export function useCreatePaymentIntent() {
  const createIntent = useMutation(api.payments.createIntent);

  return {
    mutateAsync: async (tierId: string): Promise<PaymentIntent> => {
      // This would need to call an action that generates payment address
      // For now, create a basic intent
      const expiresAt = new Date();
      expiresAt.setHours(expiresAt.getHours() + 1);
      
      const id = await createIntent({
        type: 'credits',
        amountAda: 10, // Would come from tier config
        amountLovelace: 10000000,
        paymentAddress: 'addr_mock...', // Would be generated by action
        expiresAt: expiresAt.toISOString(),
        metadata: { tierId },
      });

      const intent = await api.payments.getIntent({ id });
      
      return {
        ...intent,
        paymentId: intent._id,
        address: intent.payment_address,
        amountLovelace: intent.amount_lovelace,
        amountAda: intent.amount_ada,
        expiresAt: intent.expires_at,
      } as PaymentIntent;
    },
    mutate: () => {},
    isPending: false,
  };
}

export function usePaymentStatus(paymentId: string | null, enabled = true) {
  const intent = useQuery(
    api.payments.getIntent,
    paymentId && enabled ? { id: paymentId as Id<"payment_intents"> } : "skip"
  );

  return {
    data: intent as PendingPayment | null | undefined,
    isLoading: intent === undefined,
    error: null,
    refetch: () => {},
  };
}

export function usePendingPayments() {
  const payments = useQuery(api.payments.getPendingPayments);

  return {
    data: payments as PendingPayment[] | undefined,
    isLoading: payments === undefined,
    error: null,
  };
}

export function useCancelPayment() {
  const cancel = useMutation(api.payments.cancelIntent);

  return {
    mutateAsync: async (paymentId: string) => {
      await cancel({ id: paymentId as Id<"payment_intents"> });
    },
    mutate: () => {},
    isPending: false,
  };
}
